const languages = [
        { value: 'af', label: 'Afrikaans' },
        { value: 'sq', label: 'Albanian' },
        { value: 'am', label: 'Amharic' },
        { value: 'ar', label: 'Arabic' },
        { value: 'hy', label: 'Armenian' },
        { value: 'as', label: 'Assamese' },
        { value: 'ay', label: 'Aymara' },
        { value: 'az', label: 'Azerbaijani' },
        { value: 'bm', label: 'Bambara' },
        { value: 'eu', label: 'Basque' },
        { value: 'be', label: 'Belarusian' },
        { value: 'bn', label: 'Bengali' },
        { value: 'bho', label: 'Bhojpuri' },
        { value: 'bs', label: 'Bosnian' },
        { value: 'bg', label: 'Bulgarian' },
        { value: 'ca', label: 'Catalan' },
        { value: 'ceb', label: 'Cebuano' },
        { value: 'zh', label: 'Chinese' },
        { value: 'zh-TW', label: 'Chinese (Traditional)' },
        { value: 'co', label: 'Corsican' },
        { value: 'hr', label: 'Croatian' },
        { value: 'cs', label: 'Czech' },
        { value: 'da', label: 'Danish' },
        { value: 'dv', label: 'Dhivehi' },
        { value: 'doi', label: 'Dogri' },
        { value: 'nl', label: 'Dutch' },
        { value: 'en', label: 'English' },
        { value: 'eo', label: 'Esperanto' },
        { value: 'et', label: 'Estonian' },
        { value: 'ee', label: 'Ewe' },
        { value: 'fil', label: 'Filipino (Tagalog)' },
        { value: 'fi', label: 'Finnish' },
        { value: 'fr', label: 'French' },
        { value: 'fy', label: 'Frisian' },
        { value: 'gl', label: 'Galician' },
        { value: 'ka', label: 'Georgian' },
        { value: 'de', label: 'German' },
        { value: 'el', label: 'Greek' },
        { value: 'gn', label: 'Guarani' },
        { value: 'gu', label: 'Gujarati' },
        { value: 'ht', label: 'Haitian Creole' },
        { value: 'ha', label: 'Hausa' },
        { value: 'haw', label: 'Hawaiian' },
        { value: 'he', label: 'Hebrew' },
        { value: 'hi', label: 'Hindi' },
        { value: 'hmn', label: 'Hmong' },
        { value: 'hu', label: 'Hungarian' },
        { value: 'is', label: 'Icelandic' },
        { value: 'ig', label: 'Igbo' },
        { value: 'ilo', label: 'Ilocano' },
        { value: 'id', label: 'Indonesian' },
        { value: 'ga', label: 'Irish' },
        { value: 'it', label: 'Italian' },
        { value: 'ja', label: 'Japanese' },
        { value: 'jv', label: 'Javanese' },
        { value: 'kn', label: 'Kannada' },
        { value: 'kk', label: 'Kazakh' },
        { value: 'km', label: 'Khmer' },
        { value: 'rw', label: 'Kinyarwanda' },
        { value: 'gom', label: 'Konkani' },
        { value: 'ko', label: 'Korean' },
        { value: 'kri', label: 'Krio' },
        { value: 'ku', label: 'Kurdish' },
        { value: 'ckb', label: 'Kurdish (Sorani)' },
        { value: 'ky', label: 'Kyrgyz' },
        { value: 'lo', label: 'Lao' },
        { value: 'la', label: 'Latin' },
        { value: 'lv', label: 'Latvian' },
        { value: 'ln', label: 'Lingala' },
        { value: 'lt', label: 'Lithuanian' },
        { value: 'lg', label: 'Luganda' },
        { value: 'lb', label: 'Luxembourgish' },
        { value: 'mk', label: 'Macedonian' },
        { value: 'mai', label: 'Maithili' },
        { value: 'mg', label: 'Malagasy' },
        { value: 'ms', label: 'Malay' },
        { value: 'ml', label: 'Malayalam' },
        { value: 'mt', label: 'Maltese' },
        { value: 'mi', label: 'Maori' },
        { value: 'mr', label: 'Marathi' },
        { value: 'mni-Mtei', label: 'Meiteilon (Manipuri)' },
        { value: 'lus', label: 'Mizo' },
        { value: 'mn', label: 'Mongolian' },
        { value: 'my', label: 'Myanmar (Burmese)' },
        { value: 'ne', label: 'Nepali' },
        { value: 'no', label: 'Norwegian' },
        { value: 'ny', label: 'Nyanja (Chichewa)' },
        { value: 'or', label: 'Odia (Oriya)' },
        { value: 'om', label: 'Oromo' },
        { value: 'ps', label: 'Pashto' },
        { value: 'fa', label: 'Persian' },
        { value: 'pl', label: 'Polish' },
        { value: 'pt', label: 'Portuguese (Portugal, Brazil)' },
        { value: 'pa', label: 'Punjabi' },
        { value: 'qu', label: 'Quechua' },
        { value: 'ro', label: 'Romanian' },
        { value: 'ru', label: 'Russian' },
        { value: 'sm', label: 'Samoan' },
        { value: 'sa', label: 'Sanskrit' },
        { value: 'gd', label: 'Scots Gaelic' },
        { value: 'nso', label: 'Sepedi' }
    ]


export default languages;